dataset:
  value: "fluids.compressible.Riemann"
num_trajectories:
  value: 12
model_name:
  value: "T"
lr:
  value: 0.00005
lr_embedding_recovery:
  value: 0.0005
lr_time_embedding:
  value: 0.0005
weight_decay:
  value: 0.000001
lr_scheduler:
  value: "cosine"
warmup_ratio:
  value: 0.0
early_stopping_patience:
  value: 200
num_epochs:
  value: 0.05
batch_size:
  value: 16
max_grad_norm:
  value: 5.0